SRCS		:= AMateria.cpp Character.cpp Ice.cpp main.cpp MateriaSource.cpp Cure.cpp
OBJS		:= AMateria.o Character.o Ice.o main.o MateriaSource.o Cure.o
CXX			:= c++
CXXFLAGS	:= -std=c++98 -Wall -Wextra -Werror -g -Wshadow -Wno-shadow
NAME		:= ex03

all: ${NAME}

${NAME}: ${OBJS}
	${CXX} ${CXXFLAGS} ${OBJS} -o ${NAME}

%.o: %.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ 

clean:
	@rm -rf $(OBJS)

fclean: clean
	@rm -rf $(NAME)

.PHONY: all clean fclean re

re: fclean all
